import { Agent } from '../embinder';
import type { PlatformAction, PlatformState } from './types';

export function IncidentAnalystPage({ state, dispatch }: { state: PlatformState; dispatch: (action: PlatformAction) => void }) {
  const incident = state.incidents.find((item) => item.id === state.selectedIncidentId)!;
  const points = [72, 68, 65, 59, incident.risk, Math.max(31, incident.risk - 4)];
  return <div><p style={{ color: '#9ca8c8', fontSize: 12, letterSpacing: '0.1em', fontWeight: 800 }}>SIMULATED SIGNAL INVESTIGATION</p><h1 style={{ margin: '6px 0 8px', fontSize: 34 }}>Incident &amp; Data Analyst</h1><div style={{ display: 'grid', gridTemplateColumns: 'minmax(220px, .8fr) minmax(0, 1.5fr)', gap: 14 }}>
    <section style={{ padding: 14, border: '1px solid #2b3758', borderRadius: 12, background: '#141b31' }}><h2 style={{ marginTop: 0, fontSize: 16 }}>Incident queue</h2>{state.incidents.map((item) => <button key={item.id} type="button" onClick={() => dispatch({ type: 'select_incident', incidentId: item.id })} style={{ width: '100%', textAlign: 'left', padding: 11, marginBottom: 7, borderRadius: 9, cursor: 'pointer', color: '#f4f7ff', border: item.id === incident.id ? '1px solid #477cf6' : '1px solid #2b3758', background: '#11182c' }}><strong>{item.id}</strong><span style={{ display: 'block', color: '#9ca8c8', fontSize: 12 }}>{item.title} · risk {item.risk}</span></button>)}</section>
    <section style={{ padding: 16, border: '1px solid #2b3758', borderRadius: 12, background: '#141b31' }}><h2 style={{ marginTop: 0 }}>{incident.id} · {incident.title}</h2><p style={{ color: '#9ca8c8' }}>Confidence {incident.confidence}% — risk signal over six simulated windows.</p><div aria-label="Risk trend chart" style={{ height: 150, display: 'flex', gap: 10, alignItems: 'end', padding: '0 6px 14px', borderBottom: '1px solid #2b3758' }}>{points.map((point, index) => <div key={`${point}-${index}`} title={`Risk ${point}`} style={{ flex: 1, height: `${point}%`, minHeight: 16, borderRadius: '6px 6px 0 0', background: index >= 4 ? '#34d399' : '#477cf6' }} />)}</div><div style={{ display: 'flex', flexWrap: 'wrap', gap: 10, marginTop: 18 }}><Agent.Button name="analyze_incident" description="Analyze the selected incident and lower its simulated risk" onAct={() => dispatch({ type: 'analyze_incident' })}>Analyze {incident.id} · risk {incident.risk}</Agent.Button><Agent.Button name="move_incident_triage" description="Move the selected incident to triage" onAct={() => dispatch({ type: 'move_incident_triage' })}>Move to triage</Agent.Button></div></section>
  </div></div>;
}
