import { Agent } from '../embinder';
import type { PlatformAction, PlatformState } from './types';

const card = { padding: 16, border: '1px solid #2b3758', borderRadius: 12, background: '#141b31' };

export function MissionControlPage({ state, dispatch }: { state: PlatformState; dispatch: (action: PlatformAction) => void }) {
  const incident = state.incidents.find((item) => item.id === state.selectedIncidentId)!;
  return <div><p style={{ color: '#9ca8c8', fontSize: 12, letterSpacing: '0.1em', fontWeight: 800 }}>LIVE OPERATIONS OVERVIEW</p><h1 style={{ margin: '6px 0 8px', fontSize: 34 }}>Mission Control</h1><p style={{ color: '#9ca8c8', maxWidth: 680 }}>Coordinate the simulated response. Minder can read this surface and operate registered controls.</p>
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, minmax(0, 1fr))', gap: 12, margin: '22px 0' }}><div style={card}><span style={{ color: '#9ca8c8', fontSize: 12 }}>Current risk</span><strong style={{ display: 'block', fontSize: 28 }}>{incident.risk}/100</strong></div><div style={card}><span style={{ color: '#9ca8c8', fontSize: 12 }}>Agent status</span><strong style={{ display: 'block', fontSize: 20, textTransform: 'capitalize' }}>{state.agentStatus.replace('_', ' ')}</strong></div><div style={card}><span style={{ color: '#9ca8c8', fontSize: 12 }}>Audit events</span><strong style={{ display: 'block', fontSize: 28 }}>{state.audit.length}</strong></div></div>
    <section style={{ ...card, marginBottom: 14 }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 16 }}><div><h2 style={{ margin: 0 }}>{incident.id} · {incident.title}</h2><p style={{ color: '#9ca8c8' }}>Confidence {incident.confidence}% · {incident.affectedServices.join(' · ')}</p></div><span style={{ color: '#fbbf24', fontWeight: 800 }}>{incident.status.toUpperCase()}</span></div><div style={{ display: 'flex', flexWrap: 'wrap', gap: 10 }}><Agent.Button name="select_incident" description="Select the primary traffic anomaly incident" onAct={() => dispatch({ type: 'select_incident', incidentId: 'INC-001' })}>Focus INC-001</Agent.Button><Agent.Button name="analyze_incident" description="Analyze the selected incident and isolate the anomaly" onAct={() => dispatch({ type: 'analyze_incident' })}>Analyze incident</Agent.Button></div></section>
    <section style={card}><h2 style={{ marginTop: 0, fontSize: 17 }}>Response timeline</h2>{state.audit.slice(-3).reverse().map((entry) => <div key={entry.id} style={{ borderTop: '1px solid #263251', padding: '10px 0' }}><strong>{entry.action.replaceAll('_', ' ')}</strong><span style={{ color: '#9ca8c8', marginLeft: 8 }}>{entry.detail}</span></div>)}</section>
  </div>;
}
